// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;
using SharedProject;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;

namespace XamarinIOS
{
	public partial class _TshirtViewController : UIViewController
	{
		public _TshirtViewController (IntPtr handle) : base (handle)
		{
		}

		private static readonly HttpClient client = new HttpClient();

		private readonly string ClothesTypeUrl = "http://192.168.0.188:5000/api/values/tshirt";

		public override async void ViewDidLoad()
		{
			base.ViewDidLoad();

			client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

			HttpResponseMessage response = await client.GetAsync(ClothesTypeUrl);

			string result = await response.Content.ReadAsStringAsync();

			List<Clothes<int>> _clothes = JsonConvert.DeserializeObject<List<Clothes<int>>>(result);

			SharedData<UIImage> shared = new SharedData<UIImage>();

			foreach (Clothes<int> i1 in _clothes)
			{
				shared.AddClothesForList(i1.NameClothes, UIImage.FromBundle("t-shirt"));
			}


			TshirtTableView.RowHeight = 60;

			TshirtTableView.Source = new TshirtTVS(shared);

			TshirtTableView.Delegate = new ClothesDelegate(shared, this);

			TshirtTableView.ReloadData();

			bdButton.Clicked += (object sender, EventArgs e) =>
			{

				shared.AddClothesForList("Basic", UIImage.FromBundle("t-shirt"));

				TshirtTableView.ReloadData();

			};

		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
			
		}
	}
}
