// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace XamarinIOS
{
	public partial class _TshirtViewController : UIViewController
	{
		public _TshirtViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			var clothes = new List<Clothes>
			{
				new Clothes
				{
					Name = "T-shirt 1",
					BdImage = UIImage.FromBundle("t-shirt")
				},
				new Clothes
				{
					Name = "T-shirt 2",
					BdImage = UIImage.FromBundle("t-shirt")
				},
				new Clothes
				{
					Name = "T-shirt 3",
					BdImage = UIImage.FromBundle("t-shirt")
				},
				new Clothes
				{
					Name = "T-shirt 4",
					BdImage = UIImage.FromBundle("t-shirt")
				},
				new Clothes
				{
					Name = "T-shirt 5",
					BdImage = UIImage.FromBundle("t-shirt")
				}

			};

			TshirtTableView.RowHeight = 60;

			TshirtTableView.Source = new TshirtTVS(clothes);

			TshirtTableView.Delegate = new ClothesDelegate(clothes, this);

			TshirtTableView.ReloadData();

			bdButton.Clicked += (object sender, EventArgs e) =>
			{

				clothes.Add(new Clothes { Name = "BASIC", BdImage = UIImage.FromBundle("t-shirt") });

				TshirtTableView.ReloadData();

			};

		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
			
		}
	}
}
