// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;
using SharedProject;

namespace XamarinIOS
{
	public partial class _TshirtViewController : UIViewController
	{
		public _TshirtViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			//SharedData<int> shared = new SharedData<int>();

			//shared.AddClothesForList("T-shirt1", UIImage.FromBundle("t-shirt");

			SharedData<UIImage> shared = new SharedData<UIImage>();
			{

				shared.AddClothesForList("T-shirt1", UIImage.FromBundle("t-shirt"));

			};

			TshirtTableView.RowHeight = 60;

			TshirtTableView.Source = new TshirtTVS(shared);

			TshirtTableView.Delegate = new ClothesDelegate(shared, this);

			TshirtTableView.ReloadData();

			bdButton.Clicked += (object sender, EventArgs e) =>
			{

				shared.AddClothesForList("Basic", UIImage.FromBundle("t-shirt"));

				TshirtTableView.ReloadData();

			};

		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
			
		}
	}
}
