// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using SharedProject;

namespace XamarinIOS
{
	public partial class _TshirtCell : UITableViewCell
	{
		public _TshirtCell (IntPtr handle) : base (handle)
		{
		}

		internal void UpdateCell(Clothes<UIImage> clothess)
		{
			bdLabel.Text = clothess.NameClothes;
			bdImage.Image = clothess.bgImage;
		}
	}
}
