// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;
using SharedProject;

namespace XamarinIOS
{
    internal class TshirtTVS : UITableViewSource
    {
        SharedData<UIImage> shared = new SharedData<UIImage>();

        public TshirtTVS(SharedData<UIImage> shared)
        {
            this.shared.clothes = shared.clothes;
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = (_TshirtCell) tableView.DequeueReusableCell("cell_id", indexPath);

            var _clothes = shared.clothes[indexPath.Row];

            cell.UpdateCell(_clothes);

            return cell;
        }

        public override nint RowsInSection(UITableView tableview, nint section)
        {
            return shared.clothes.Count;
        }

    }
}