// This file has been autogenerated from a class added in the UI designer.

using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using Foundation;
using Newtonsoft.Json;
using SharedProject;
using UIKit;

namespace XamarinIOS
{
    internal class ClothesDelegate : UITableViewDelegate
    {
        private SharedData<UIImage> shared = new SharedData<UIImage>();
        private _TshirtViewController tshirtviewcontroller;
        private SocsViewController socsViewController;
        private HoodieViewController hoodieViewController;
        private _CapViewController capViewController;

        private static readonly HttpClient client = new HttpClient();
        private readonly string AllClothesUrl = "http://192.168.0.188:5000/api/values/allclothes/";
        private readonly string DeleteClothesUrl = "http://192.168.0.188:5000/api/values/deleteclothes";
        private readonly string ChangeClothesUrl = "http://192.168.0.188:5000/api/values/changeclothes";

        public ClothesDelegate(SharedData<UIImage> shared)
        {
            this.shared.clothes = shared.clothes;
        }

        public ClothesDelegate(SharedData<UIImage> shared, _TshirtViewController tshirtviewcontroller) : this(shared)
        {
            this.tshirtviewcontroller = tshirtviewcontroller;
        }

        public ClothesDelegate(SharedData<UIImage> shared, SocsViewController socsViewController) : this(shared)
        {
            this.socsViewController = socsViewController;
        }

        public ClothesDelegate(SharedData<UIImage> shared, HoodieViewController hoodieViewController) : this(shared)
        {
            this.hoodieViewController = hoodieViewController;
        }

        public ClothesDelegate(SharedData<UIImage> shared, _CapViewController capViewController) : this(shared)
        {
            this.capViewController = capViewController;
        }

        [Export("tableView:editActionsForRowAtIndexPath:")]
        public UITableViewRowAction[] EditActionsForRow(UITableView tableView, NSIndexPath indexPath)
        {
            var action = UITableViewRowAction.Create(UITableViewRowActionStyle.Default, "delete", async (arg1, arg2) =>
            {

                var selected = shared.clothes[indexPath.Row];
                selected.bgImage = null;



                var json = JsonConvert.SerializeObject(selected, Formatting.Indented);
                var stringContent = new StringContent(json, Encoding.UTF8, "application/json");

                HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, DeleteClothesUrl);
                request.Content = new StringContent(json, Encoding.UTF8, "application/json");
                string _result = await request.Content.ReadAsStringAsync();

                HttpResponseMessage _response = await client.PostAsync(DeleteClothesUrl, stringContent);

                shared.clothes.Remove(selected);

                tableView.ReloadData();
            });

            var action1 = UITableViewRowAction.Create(UITableViewRowActionStyle.Normal, "change", (arg1, arg2) =>
            {
                UIAlertController alert = UIAlertController.Create("Alert", "Change", UIAlertControllerStyle.Alert);
                UITextField field = null;


                alert.AddTextField(async (textField) =>
                {

                    field = textField;

                    var selected = shared.clothes[indexPath.Row];
                   // selected.bgImage = null;


                    field.Placeholder = "placeholder";
                    field.Text = selected.NameClothes;
                    field.AutocorrectionType = UITextAutocorrectionType.No;
                    field.KeyboardType = UIKeyboardType.Default;
                    field.ReturnKeyType = UIReturnKeyType.Done;
                    field.ClearButtonMode = UITextFieldViewMode.WhileEditing;

                   

                });


                alert.AddAction(UIAlertAction.Create("Cancel", UIAlertActionStyle.Cancel, (actionCancel) =>
                {


                }));

                alert.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, async (actionOK) =>
                {
                    var selected = shared.clothes[indexPath.Row];
                    selected.NameClothes = field.Text;

                    Clothes<int> clothes = new Clothes<int>();
                    clothes.bgImage = 0;
                    clothes.id = selected.id;
                    clothes.idType = selected.idType;
                    clothes.NameClothes = selected.NameClothes;

                    var json = JsonConvert.SerializeObject(clothes, Formatting.Indented);
                    var stringContent = new StringContent(json, Encoding.UTF8, "application/json");

                    HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, ChangeClothesUrl);
                    request.Content = new StringContent(json, Encoding.UTF8, "application/json");
                    string _result = await request.Content.ReadAsStringAsync();

                    HttpResponseMessage _response = await client.PostAsync(ChangeClothesUrl, stringContent);

                    tableView.ReloadData();

                }));

                if (tshirtviewcontroller != null)
                {
                    tshirtviewcontroller.PresentViewController(alert, true, null);
                } else if (hoodieViewController != null)
                {
                    hoodieViewController.PresentViewController(alert, true, null);
                } else if (capViewController != null)
                {
                    capViewController.PresentViewController(alert, true, null);
                } else
                {
                    socsViewController.PresentViewController(alert, true, null);
                }


            });


            return new UITableViewRowAction[] { action, action1 };

        }
    }
}
