// This file has been autogenerated from a class added in the UI designer.

using System.Collections.Generic;
using Foundation;
using UIKit;

namespace XamarinIOS
{
    internal class ClothesDelegate : UITableViewDelegate
    {
        private List<Clothes> clothes;
        private _TshirtViewController tshirtviewcontroller;
        private SocsViewController socsViewController;
        private HoodieViewController hoodieViewController;
        private _CapViewController capViewController;

        public ClothesDelegate(List<Clothes> clothes)
        {
            this.clothes = clothes;
        }

        public ClothesDelegate(List<Clothes> clothes, _TshirtViewController tshirtviewcontroller) : this(clothes)
        {
            this.tshirtviewcontroller = tshirtviewcontroller;
        }

        public ClothesDelegate(List<Clothes> clothes, SocsViewController socsViewController) : this(clothes)
        {
            this.socsViewController = socsViewController;
        }

        public ClothesDelegate(List<Clothes> clothes, HoodieViewController hoodieViewController) : this(clothes)
        {
            this.hoodieViewController = hoodieViewController;
        }

        public ClothesDelegate(List<Clothes> clothes, _CapViewController capViewController) : this(clothes)
        {
            this.capViewController = capViewController;
        }

        [Export("tableView:editActionsForRowAtIndexPath:")]
        public UITableViewRowAction[] EditActionsForRow(UITableView tableView, NSIndexPath indexPath)
        {
            var action = UITableViewRowAction.Create(UITableViewRowActionStyle.Default, "delete", (arg1, arg2) =>
            {

                var selected = clothes[indexPath.Row];

                clothes.Remove(selected);

                tableView.ReloadData();
            });

            var action1 = UITableViewRowAction.Create(UITableViewRowActionStyle.Normal, "change", (arg1, arg2) =>
            {
                UIAlertController alert = UIAlertController.Create("Alert", "Change", UIAlertControllerStyle.Alert);
                UITextField field = null;


                alert.AddTextField((textField) =>
                {

                    field = textField;

                    var selected = clothes[indexPath.Row];


                    field.Placeholder = "placeholder";
                    field.Text = selected.Name;
                    field.AutocorrectionType = UITextAutocorrectionType.No;
                    field.KeyboardType = UIKeyboardType.Default;
                    field.ReturnKeyType = UIReturnKeyType.Done;
                    field.ClearButtonMode = UITextFieldViewMode.WhileEditing;

                });


                alert.AddAction(UIAlertAction.Create("Cancel", UIAlertActionStyle.Cancel, (actionCancel) =>
                {


                }));

                alert.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, (actionOK) =>
                {
                    var selected = clothes[indexPath.Row];
                    selected.Name = field.Text;
                    tableView.ReloadData();

                }));

                if (tshirtviewcontroller != null)
                {
                    tshirtviewcontroller.PresentViewController(alert, true, null);
                } else if (hoodieViewController != null)
                {
                    hoodieViewController.PresentViewController(alert, true, null);
                } else if (capViewController != null)
                {
                    capViewController.PresentViewController(alert, true, null);
                } else
                {
                    socsViewController.PresentViewController(alert, true, null);
                }


            });


            return new UITableViewRowAction[] { action, action1 };

        }
    }
}
