// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace XamarinIOS
{
	public partial class HoodieViewController : UIViewController
	{
		public HoodieViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			var clothes = new List<Clothes>
			{
				new Clothes
				{
					Name = "Hoodie 1",
					BdImage = UIImage.FromBundle("hoodie")
				},
				new Clothes
				{
					Name = "Hoodie 2",
					BdImage = UIImage.FromBundle("hoodie")
				},
				new Clothes
				{
					Name = "Hoodie 3",
					BdImage = UIImage.FromBundle("hoodie")
				},
				new Clothes
				{
					Name = "Hoodie 4",
					BdImage = UIImage.FromBundle("hoodie")
				},
				new Clothes
				{
					Name = "Hoodie 5",
					BdImage = UIImage.FromBundle("hoodie")
				}

			};

			HoodieTableView.RowHeight = 60;

			HoodieTableView.Source = new HoodieTVS(clothes);

			HoodieTableView.Delegate = new ClothesDelegate(clothes, this);

			HoodieTableView.ReloadData();

			bdButton.Clicked += (object sender, EventArgs e) =>
			{
				clothes.Add(new Clothes { Name = "BASIC", BdImage = UIImage.FromBundle("hoodie") });

				HoodieTableView.ReloadData();
			};

		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
		}
	}
}
