// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XamarinIOS
{
	public partial class HoodieCell : UITableViewCell
	{
		public HoodieCell(IntPtr handle) : base(handle)
		{
		}

		internal void UpdateCell(Clothes clothess)
		{
			bdLabel.Text = clothess.Name;
			bdImage.Image = clothess.BdImage;
		}
	}
}
