// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using SharedProject;
using UIKit;

namespace XamarinIOS
{
	public partial class HoodieViewController : UIViewController
	{
		public HoodieViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

            SharedData<UIImage> shared = new SharedData<UIImage>();
            {

                shared.AddClothesForList("Hoodie1", UIImage.FromBundle("hoodie"));

                //	new Clothes
                //	{
                //		Name = "Hoodie 1",
                //		BdImage = UIImage.FromBundle("hoodie")
                //	},
                //	new Clothes
                //	{
                //		Name = "Hoodie 2",
                //		BdImage = UIImage.FromBundle("hoodie")
                //	},
                //	new Clothes
                //	{
                //		Name = "Hoodie 3",
                //		BdImage = UIImage.FromBundle("hoodie")
                //	},
                //	new Clothes
                //	{
                //		Name = "Hoodie 4",
                //		BdImage = UIImage.FromBundle("hoodie")
                //	},
                //	new Clothes
                //	{
                //		Name = "Hoodie 5",
                //		BdImage = UIImage.FromBundle("hoodie")
                //	}

            };

            HoodieTableView.RowHeight = 60;

			HoodieTableView.Source = new HoodieTVS(shared);

			HoodieTableView.Delegate = new ClothesDelegate(shared, this);

			HoodieTableView.ReloadData();

			bdButton.Clicked += (object sender, EventArgs e) =>
			{
                shared.AddClothesForList("Basic", UIImage.FromBundle("hoodie"));

                HoodieTableView.ReloadData();
			};

		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
		}
	}
}
