// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace XamarinIOS
{
    internal class SocsTVS : UITableViewSource
    {
        private List<Clothes> clothes;

        public SocsTVS(List<Clothes> clothes)
        {
            this.clothes = clothes;
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = (SocsCell)tableView.DequeueReusableCell("cell_id", indexPath);

            var _clothes = clothes[indexPath.Row];

            cell.UpdateCell(_clothes);

            return cell;
        }

        public override nint RowsInSection(UITableView tableview, nint section)
        {
            return clothes.Count;
        }
    }
}