// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using Foundation;
using Newtonsoft.Json;
using SharedProject;
using UIKit;

namespace XamarinIOS
{
	public partial class SocsViewController : UIViewController
	{
		public SocsViewController(IntPtr handle) : base(handle)
		{
		}

		private static readonly HttpClient client = new HttpClient();

		private readonly string ClothesTypeUrl = "http://192.168.0.188:5000/api/values/socs";

		public override async void ViewDidLoad()
		{
			base.ViewDidLoad();

			client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

			HttpResponseMessage response = await client.GetAsync(ClothesTypeUrl);

			string result = await response.Content.ReadAsStringAsync();

			List<Clothes<int>> _clothes = JsonConvert.DeserializeObject<List<Clothes<int>>>(result);

			SharedData<UIImage> shared = new SharedData<UIImage>();

			foreach (Clothes<int> i1 in _clothes)
			{
				shared.AddClothesForList(i1.NameClothes, UIImage.FromBundle("socs"));
			}

			SocsTableView.RowHeight = 60;

			SocsTableView.Source = new SocsTVS(shared);

			SocsTableView.Delegate = new ClothesDelegate(shared, this);

			SocsTableView.ReloadData();


			bdButton.Clicked += (object sender, EventArgs e) =>
			{
				shared.AddClothesForList("Basic", UIImage.FromBundle("socs"));

				SocsTableView.ReloadData();
			};

		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
		}
	}
}
