// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using SharedProject;
using UIKit;

namespace XamarinIOS
{
	public partial class SocsViewController : UIViewController
	{
		public SocsViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			SharedData<UIImage> shared = new SharedData<UIImage>();
			{
				shared.AddClothesForList("Socs1", UIImage.FromBundle("socs"));

			};

			SocsTableView.RowHeight = 60;

			SocsTableView.Source = new SocsTVS(shared);

			SocsTableView.Delegate = new ClothesDelegate(shared, this);

			SocsTableView.ReloadData();


			bdButton.Clicked += (object sender, EventArgs e) =>
			{
				shared.AddClothesForList("Basic", UIImage.FromBundle("socs"));

				SocsTableView.ReloadData();
			};

		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
		}
	}
}
