// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XamarinIOS
{
	public partial class _bdCell : UITableViewCell
	{
		public _bdCell (IntPtr handle) : base (handle)
		{
		}

		internal void UpdateCell(Clothes clothess)
		{
			_bdLabel.Text = clothess.Name;
			_bdImage.Image = clothess.BdImage;
		}
	}
}
