// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace XamarinIOS
{
	public partial class _bdView : UIViewController
	{
		public _bdView(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			

			var clothes = new List<Clothes>
			{
				new Clothes
				{
					Name = "T-SHIRT 1",
					BdImage = UIImage.FromBundle("t-shirt")
				},
				new Clothes
				{
					Name = "T-SHIRT 2",
					BdImage = UIImage.FromBundle("t-shirt")
				},
				new Clothes
				{
					Name = "T-SHIRT 3",
					BdImage = UIImage.FromBundle("t-shirt")
				},
				new Clothes
				{
					Name = "T-SHIRT 4",
					BdImage = UIImage.FromBundle("t-shirt")
				},
				new Clothes
				{
					Name = "T-SHIRT 5",
					BdImage = UIImage.FromBundle("t-shirt")
				}



			};

			_bdTable.RowHeight = 70;

			_bdTable.Source = new ClothesTVS(clothes);

			_bdTable.Delegate = new ClothesDelegate(clothes);

			_bdTable.ReloadData();

			_bdButton.TouchUpInside += (object sender, EventArgs e) =>
			{
				clothes.Add(new Clothes { Name = "BASIC", BdImage = UIImage.FromBundle("t-shirt") }) ;

				_bdTable.ReloadData();
			};


		}


		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
			// Release any cached data, images, etc that aren't in use.
		}
	}
}
