// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XamarinIOS
{
	public partial class BdClothesTableView : UITableView
	{
		public BdClothesTableView (IntPtr handle) : base (handle)
		{
		}
	}
}
