// This file has been autogenerated from a class added in the UI designer.

using System.Collections.Generic;
using Foundation;
using UIKit;

namespace XamarinIOS
{
    internal class ClothesDelegate : UITableViewDelegate
    {
        private List<Clothes> clothes;

        public ClothesDelegate(List<Clothes> clothes)
        {
            this.clothes = clothes;
            
        }

        [Export("tableView:editActionsForRowAtIndexPath:")]
        public UITableViewRowAction[] EditActionsForRow(UITableView tableView, NSIndexPath indexPath)
        {
            var action = UITableViewRowAction.Create(UITableViewRowActionStyle.Default, "delete", (arg1, arg2) =>
            {

                var selected = clothes[indexPath.Row];

                clothes.Remove(selected);

                tableView.ReloadData();
            });

            
            return new UITableViewRowAction[] { action };
        }
    }
}