// This file has been autogenerated from a class added in the UI designer.

using UIKit;

namespace XamarinIOS
{
    internal class Clothes
    {
        public string Name
        {
            get;

            set;
        }

        public UIImage BdImage
        {
            get;

            set;
        }
    }
}