// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XamarinIOS
{
	public partial class EmployeeCell : UITableViewCell
	{
		public EmployeeCell (IntPtr handle) : base (handle)
		{
		}

        internal void UpdateCell(Employee employee)
        {
            bdLabelCell1.Text = employee.Name;
            bdImageCell.Image = employee.BdImage;
        }
    }
}
