// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XamarinIOS
{
	public partial class _CapCell : UITableViewCell
	{
		public _CapCell (IntPtr handle) : base (handle)
		{ 
		}

		internal void UpdateCell(Clothes clothess)
		{
			bdLabel.Text = clothess.Name;
			bdImage.Image = clothess.BdImage;
		}
	}
}
