// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using Foundation;
using Newtonsoft.Json;
using SharedProject;
using UIKit;

namespace XamarinIOS
{
	public partial class _CapViewController : UIViewController
	{
		public _CapViewController(IntPtr handle) : base(handle)
		{
		}

		private static readonly HttpClient client = new HttpClient();

		private readonly string ClothesTypeUrl = "http://192.168.0.188:5000/api/values/cap";
		private readonly string AddUrl = "http://192.168.0.188:5000/api/values";

		public override async void ViewDidLoad()
		{
			base.ViewDidLoad();

			client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

			HttpResponseMessage response = await client.GetAsync(ClothesTypeUrl);

			string result = await response.Content.ReadAsStringAsync();

			List<Clothes<int>> _clothes = JsonConvert.DeserializeObject<List<Clothes<int>>>(result);

			SharedData<UIImage> shared = new SharedData<UIImage>();

			foreach (Clothes<int> i1 in _clothes)
			{
				shared.AddClothesForList(i1.NameClothes, UIImage.FromBundle("caps"), 9, i1.id);
			}

			CapTableView.RowHeight = 60;

            CapTableView.Source = new CapTVS(shared);

            CapTableView.Delegate = new ClothesDelegate(shared, this);

            CapTableView.ReloadData();

            bdButton.Clicked += async (object sender, EventArgs e) =>
			{
				var cl = new Clothes<int>
				{
					idType = 9,
					NameClothes = "Cap",
					bgImage = 0
				};

				var json = JsonConvert.SerializeObject(cl, Formatting.Indented);
				var stringContent = new StringContent(json, Encoding.UTF8, "application/json");

				HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, AddUrl);
				request.Content = new StringContent(json, Encoding.UTF8, "application/json");
				string _result = await request.Content.ReadAsStringAsync();

				HttpResponseMessage _response = await client.PostAsync(AddUrl, stringContent);

				shared.AddClothesForList(cl.NameClothes, UIImage.FromBundle("caps"), cl.idType, cl.id);

				CapTableView.ReloadData();
			};

		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
			
		}
	}
}
