// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using SharedProject;
using UIKit;

namespace XamarinIOS
{
	public partial class _CapViewController : UIViewController
	{
		public _CapViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			SharedData<UIImage> shared = new SharedData<UIImage>();
			{
				shared.AddClothesForList("T-shirt1", UIImage.FromBundle("t-shirt"));

			};

            CapTableView.RowHeight = 60;

            CapTableView.Source = new CapTVS(shared);

            CapTableView.Delegate = new ClothesDelegate(shared, this);

            CapTableView.ReloadData();

            bdButton.Clicked += (object sender, EventArgs e) =>
			{
				shared.AddClothesForList("Basic", UIImage.FromBundle("cap"));

				CapTableView.ReloadData();
			};

		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
			
		}
	}
}
