// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace XamarinIOS
{
	public partial class _CapViewController : UIViewController
	{
		public _CapViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			var clothes = new List<Clothes>
			{
				new Clothes
				{
					Name = "Cap 1",
					BdImage = UIImage.FromBundle("caps")
				},
				new Clothes
				{
					Name = "Cap 2",
					BdImage = UIImage.FromBundle("caps")
				},
				new Clothes
				{
					Name = "Cap 3",
					BdImage = UIImage.FromBundle("caps")
				},
				new Clothes
				{
					Name = "Cap 4",
					BdImage = UIImage.FromBundle("caps")
				},
				new Clothes
				{
					Name = "Cap 5",
					BdImage = UIImage.FromBundle("caps")
				}

			};

			CapTableView.RowHeight = 60;

			CapTableView.Source = new CapTVS(clothes);

			CapTableView.Delegate = new ClothesDelegate(clothes, this);

			CapTableView.ReloadData();

			bdButton.Clicked += (object sender, EventArgs e) =>
			{
				clothes.Add(new Clothes { Name = "BASIC", BdImage = UIImage.FromBundle("caps") });

				CapTableView.ReloadData();
			};

		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
			
		}
	}
}
