// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XamarinIOS
{
	public partial class _bdNavigation : UINavigationController
	{
		public _bdNavigation (IntPtr handle) : base (handle)
		{

		}
	}
}
